apiVersion: v1
kind: Namespace
metadata:
  #  creationTimestamp: null
  name: infosys

apiVersion: v1
kind: Pod
metadata:
  #  creationTimestamp: null
  labels:
    run: demo1
  name: demo1
  namespace: infosys
spec:
  containers:
  - image: adikarthik/demo
    name: demo1
    ports:
    - containerPort: 9090
      #   resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

