apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  namespace: sunilns2
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80              # Port exposed by the service
      targetPort: 8080      # Port on the container
      protocol: TCP         # Protocol to use (default is TCP)

