apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  namespace: sunilns2
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - port: 80            # Port that the service exposes
      targetPort: 8080    # Port on the pods that the service forwards traffic to
      protocol: TCP       # Protocol to use (default is TCP)

