apiVersion: v1
kind: Service
metadata:
  name: demo1-service
  namespace: infosys
spec:
  selector:
    run: demo1   # Matches the label in your pod
  ports:
  - protocol: TCP
    port: 80         # Port to expose the Service
    targetPort: 9090 # Port where the application in the Pod is listening
  type: ClusterIP    # Service type: ClusterIP, NodePort, LoadBalancer

